_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 7c27905a-d059-4ea7-a22c-d0a7e7644697
name: 'Local Employee Management Portal'
mail: practice@main.drupal.com
slogan: ''
page:
  403: ''
  404: ''
  front: /homepage
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
